ingress:
  enabled: true
  className: nginx
  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      location /metrics {
        deny all;
        default_type application/json;
        return 404;
      }
  
  tls:
    enabled: true
    secretName: vedcsn-tls
    hosts:
      - workers.vedcsn.com
  
  hosts:
    - host: workers.vedcsn.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: vm-agents-service
            port: 8000

namespace: default