apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      location /metrics {
        deny all;
        return 403;
      }
    cert-manager.io/cluster-issuer: letsencrypt-prod  
spec:
  ingressClassName: nginx
  tls:  
  - hosts:
    - workers.vedcsn.com
    secretName: vedcsn-tls
  rules:
    - host: workers.vedcsn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vm-agents-service
                port:
                  number: 8000
    - hosts: shop.vedcsn.com
      http:
        paths:  
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: vm-agents-service
                  port:
                    number: 8000
