apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/server-snippet: |
    #   location /metrics {
    #     deny all;
    #     default_type application/json;
    #     return 404;
    #   }
    cert-manager.io/cluster-issuer: letsencrypt-prod  
spec:
  ingressClassName: nginx
  tls:  
  - hosts:
    - backend.vedcsn.com
    - nginx.vedcsn.com
    - workers.vedcsn.com
    secretName: vedcsn-tls
  rules:
    - host: backend.vedcsn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
    
    - host: nginx.vedcsn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

    - host: workers.vedcsn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vm-agents-service
                port:
                  number: 8000