apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    namespace: dev
    user: ved
  name: ved-context
current-context: ved-context
users:
- name: ved
  user:
    client-certificate-data: 
    client-key-data: 
