[project]
name = "prometheus-functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "loguru>=0.7.3",
    "prometheus-client>=0.24.1",
    "uvicorn[standard]>=0.30.0",
]
